#!/bin/bash

#Configuration to the Rucio server 1.8.5.post1
export RUCIO_HOME=/cvmfs/xenon.opensciencegrid.org/software/rucio-py27/1.8.3/rucio
export RUCIO_ACCOUNT=xenon-analysis
export X509_USER_PROXY=/home/bauermeister/proxy_xenon/x509up_own

