#!/bin/bash
# Enter the XENONnT (singularity + conda) environment on dali/midway


##
# Argument parsing
# (sorry, I don't know bash well, just copy/pasted/edited from
# https://stackoverflow.com/questions/192249/
##

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in

    -j|--jupyter)
    JUPYTER=YES
    shift  # past argument
    ;;


    -p|--port)
    PORT="$2"
    shift # past argument
    shift # past value
    ;;

    -n|--container)
    CONTAINER_NAME="$2"
    shift # past argument
    shift # past value
    ;;

    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$CONTAINER_NAME" ]
then 
    echo "Container name not given, using latest container"
    CONTAINER_NAME="osgvo-xenon:latest"
fi

echo "JUPYTER = ${JUPYTER}"
echo "PORT = ${PORT}"
echo "CONTAINERNAME = ${CONTAINER_NAME}"

INNER_SCRIPT="/project2/lgrandi/xenonnt/development/_xentenv_inner.sh"
if [ ! -z "$JUPYTER" ]
then
    INNER_SCRIPT="${INNER_SCRIPT} -j ${PORT}"
fi
echo "INNER_SCRIPT = ${INNER_SCRIPT}"

CONTAINER_PATH=/cvmfs/singularity.opensciencegrid.org/opensciencegrid
SINGULARITY_CACHEDIR=/scratch/midway2/$USER/singularity_cache

echo "Loading singularity"
module load singularity

echo "Container build info:"
cat $CONTAINER_PATH/$CONTAINER_NAME/image-build-info.txt

echo "Loading $CONTAINER_NAME"

singularity exec --bind /cvmfs/ --bind /project/ --bind /project2/ --bind /scratch/midway2/$USER --bind /dali $CONTAINER_PATH/$CONTAINER_NAME $INNER_SCRIPT

