#!/bin/bash

#export RUCIO_HOME=$CONDA_PREFIX #Not necessesary since already done in original init script
export RUCIO_ACCOUNT=xenon-analysis
export X509_USER_PROXY=/home/bauermeister/proxy_xenon/x509up_own
